UPDATE quick_alert_rule_metric SET name_en = 'Average Request Latency' WHERE name = '平均请求延时' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Request Error Rate' WHERE name = '请求错误率' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Disk Usage' WHERE name = '磁盘使用率' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Average Request Latency Increased by More Than 20% Compared to Yesterday' WHERE name = '平均请求延时相比昨天升高20%以上' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Log Error Count Increased by More Than 20% Compared to Yesterday' WHERE name = '日志错误数相比昨天升高20%以上' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Request Error Rate Increased by More Than 20% Compared to Yesterday' WHERE name = '请求错误率相比昨天升高20%以上' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Network Inbound Throughput' WHERE name = '网络入吞吐量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Disk Read Speed' WHERE name = '磁盘读速度' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Disk Write Speed' WHERE name = '磁盘写速度' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'CPU Load' WHERE name = 'CPU负载' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'CPU IO Wait' WHERE name = 'CPU IO Wait' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Disk IO Utilization' WHERE name = '磁盘IO利用率' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Network RTT Latency' WHERE name = '网络RTT延时' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Last Run Time' WHERE name = '容器上次运行时间' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Persistent Volume Usage' WHERE name = '容器持久卷使用率' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container CPU Usage' WHERE name = '容器CPU使用率' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container cpu_cfs_throttled' WHERE name = '容器cpu_cfs_throttled' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Memory Usage' WHERE name = '容器内存使用率' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container CPU Utilization (system)' WHERE name = '容器 CPU 利用率(system)' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container CPU Utilization (user)' WHERE name = '容器 CPU 利用率(user)' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container CPU Utilization (overall, value not greater than 100)' WHERE name = '容器 CPU 利用率(整体，值不会大于 100)' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container CPU Utilization (overall, value may be greater than 100)' WHERE name = '容器 CPU 利用率(整体，值可能会大于 100)' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container CPU Periods per Second' WHERE name = '容器 CPU 每秒有多少 period' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container CPU Throttled Periods per Second' WHERE name = '容器 CPU 每秒被 throttle 的 period 量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container CPU Throttle Ratio' WHERE name = '容器 CPU 被 throttle 的比例' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Filesystem Usage' WHERE name = '容器 filesystem 使用率' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Filesystem Used' WHERE name = '容器 filesystem 使用量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Filesystem Current IO Operations' WHERE name = '容器 filesystem 当前 IO 次数' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Filesystem Current IO Operations' WHERE name = '容器 filesystem 当前 IO 次数' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Filesystem Total' WHERE name = '容器 filesystem 总量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Inode Free' WHERE name = '容器 inode free 量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Inode Total' WHERE name = '容器 inode total 量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Inode Usage' WHERE name = '容器 inode 使用率' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container IO Write Bytes per Second' WHERE name = '容器 IO 每秒写入 byte 量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container IO Read Bytes per Second' WHERE name = '容器 IO 每秒读取 byte 量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Memory Cache' WHERE name = '容器 memory cache 量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Memory Usage (Usage)' WHERE name = '容器 memory 使用率(Usage)' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Memory Usage (Working Set)' WHERE name = '容器 memory 使用率(Working Set)' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Memory Used (mapped_file)' WHERE name = '容器 memory 使用量(mapped_file)' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Memory Used (RSS)' WHERE name = '容器 memory 使用量(RSS)' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Memory Used (Swap)' WHERE name = '容器 memory 使用量(Swap)' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Memory Used (Usage)' WHERE name = '容器 memory 使用量(Usage)' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Memory Used (Working Set)' WHERE name = '容器 memory 使用量(Working Set)' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Memory Allocation Failures per Second' WHERE name = '容器 memory 分配失败次数(每秒)' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Memory Limit' WHERE name = '容器 memory 限制量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Network Send Bits per Second' WHERE name = '容器 net 每秒发送 bit 量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Network Send Packets per Second' WHERE name = '容器 net 每秒发送数据包数量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Network Send Dropped Packets per Second' WHERE name = '容器 net 每秒发送时 drop 包数量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Network Send Error Packets per Second' WHERE name = '容器 net 每秒发送错包数' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Network Receive Bits per Second' WHERE name = '容器 net 每秒接收 bit 量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Network Receive Packets per Second' WHERE name = '容器 net 每秒接收数据包数量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Network Receive Dropped Packets per Second' WHERE name = '容器 net 每秒接收时 drop 包数量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Network Receive Error Packets per Second' WHERE name = '容器 net 每秒接收错包数' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Maximum Allowed Threads' WHERE name = '容器允许运行的最大线程数' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Soft Ulimit for Process 1 in Container' WHERE name = '容器内 1 号进程 soft ulimit 值' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Uptime' WHERE name = '容器已经运行的时间' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Current Open Sockets' WHERE name = '容器当前打开套接字数量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Current Open File Handles' WHERE name = '容器当前打开文件句柄数量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Current Running Threads' WHERE name = '容器当前运行的线程数' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Current Running Processes' WHERE name = '容器当前运行的进程数' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container GPU Memory Used' WHERE name = '容器正在使用的 GPU 加速卡内存量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Total GPU Memory Available' WHERE name = '容器总 GPU 加速卡可用内存量' AND name_en IS NULL;
UPDATE quick_alert_rule_metric SET name_en = 'Container Metric Loss Duration' WHERE name = '容器指标丢失时长' AND name_en IS NULL;